name: Invincible Sync
on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: python scraper.py
      - run: |
          git config --global user.name "Jarvis-Agent"
          git config --global user.email "agent@invincible.energy"
          git add index.html
          git commit -m "10min Sync" || echo "no changes"
          git push
          
